// Generated by Claude, 2026-08-14
// Canonical arena (bump / linear) allocator over a pre-allocated buffer.
//
// The whole idea: allocation is a pointer bump, deallocation is a no-op.
// You never free individual objects; you reset the whole arena at once.
// That trades away per-object lifetime control for allocations that cost
// a few instructions and never touch the system allocator.
//
// Typical use is a phase-scoped workload: allocate freely during a tick /
// request / frame, then reset() at the boundary. Compare with ObjectPool
// in pool.cpp, which is the opposite trade: same-sized slots that CAN be
// individually released, via a free list.

#include <cstddef>
#include <cstdint>
#include <memory>
#include <new>
#include <utility>

class Arena {
public:
    // Non-owning: the arena bumps through a buffer the caller supplies.
    // Keeping ownership out of the arena is what lets the same class sit
    // on top of a stack array, a static buffer, or a heap block.
    Arena(std::byte* buffer, std::size_t size) noexcept
        : begin_(buffer), current_(buffer), end_(buffer + size) {}

    Arena(const Arena&) = delete;
    Arena& operator=(const Arena&) = delete;

    // Raw allocation. Returns nullptr when the arena is exhausted rather
    // than throwing, so callers on a hot path can fall back or drop.
    void* allocate(std::size_t bytes, std::size_t alignment) noexcept {
        void* ptr = current_;
        std::size_t space = static_cast<std::size_t>(end_ - current_);

        // std::align does the round-up-to-alignment and the bounds check
        // in one step, and reports failure by returning nullptr. Doing it
        // by hand invites overflow bugs when current_ + alignment wraps.
        if (std::align(alignment, bytes, ptr, space) == nullptr) {
            return nullptr;
        }

        current_ = static_cast<std::byte*>(ptr) + bytes;
        return ptr;
    }

    // Allocate storage for a T and construct it in place.
    // Note the arena never runs ~T(): see reset() below.
    template <typename T, typename... Args>
    T* create(Args&&... args) {
        void* mem = allocate(sizeof(T), alignof(T));
        if (mem == nullptr) {
            return nullptr;
        }
        return ::new (mem) T(std::forward<Args>(args)...);
    }

    // Allocate a contiguous, default-constructed array of n objects.
    template <typename T>
    T* create_array(std::size_t n) {
        void* mem = allocate(sizeof(T) * n, alignof(T));
        if (mem == nullptr) {
            return nullptr;
        }
        return ::new (mem) T[n];
    }

    // Release everything at once. This does NOT run destructors: the arena
    // does not track what was constructed in it. That is the deliberate
    // trade — it is only safe for trivially destructible types, or when
    // the caller destroys objects itself before resetting.
    void reset() noexcept { current_ = begin_; }

    // A scope-based partial reset: rewind to a saved point on scope exit.
    // Lets an inner phase borrow arena space without disturbing the outer.
    class Marker {
    public:
        explicit Marker(Arena& arena) noexcept
            : arena_(arena), saved_(arena.current_) {}
        ~Marker() noexcept { arena_.current_ = saved_; }

        Marker(const Marker&) = delete;
        Marker& operator=(const Marker&) = delete;

    private:
        Arena& arena_;
        std::byte* saved_;
    };

    std::size_t capacity() const noexcept {
        return static_cast<std::size_t>(end_ - begin_);
    }
    std::size_t used() const noexcept {
        return static_cast<std::size_t>(current_ - begin_);
    }
    std::size_t remaining() const noexcept {
        return static_cast<std::size_t>(end_ - current_);
    }

private:
    std::byte* begin_;    // start of the backing buffer
    std::byte* current_;  // bump pointer: next free byte
    std::byte* end_;      // one past the last usable byte
};

// Convenience wrapper that owns its storage inline, sized at compile time.
// No heap allocation at all — the buffer is a member, like FixedObjectPool
// in pool.cpp.
template <std::size_t N>
class FixedArena : public Arena {
public:
    FixedArena() noexcept : Arena(storage_, N) {}

private:
    // max_align_t alignment so the buffer can host any non-over-aligned
    // type; allocate() still re-aligns per request on top of this.
    alignas(std::max_align_t) std::byte storage_[N];
};

int main() {
    return 0;
}
