// Generated by Claude, 2026-08-17
// BinaryMessageParser_v1.0.hpp
//
// Canonical fixed-layout binary message parser.
//
// Wire format assumed (big-endian / network byte order on the wire):
//
//   Header (8 bytes)
//     [0]      uint8_t   version
//     [1]      uint8_t   msg_type
//     [2..3]   uint16_t  payload_length   (bytes following the header)
//     [4..7]   uint32_t  sequence
//
//   Body layout is fixed per msg_type. Example body shown below is a
//   simplified quote:
//     [0..3]   uint32_t  instrument_id
//     [4..11]  int64_t   price          (fixed-point, e.g. 1e-6 ticks)
//     [12..15] uint32_t  size
//
// Design stance:
//   - Never reinterpret_cast the buffer to a struct. That is undefined
//     behaviour on misaligned reads and wrong on a little-endian host.
//     Fields are pulled out with memcpy and byte-swapped explicitly.
//   - Every read is bounds-checked against the remaining buffer. A
//     truncated or malicious frame must not over-read.
//   - Parsing returns a status rather than throwing, so the hot path
//     stays exception-free and the caller decides drop vs resync.


#include <cstdint>
#include <cstddef>
#include <cstring>
#include <bit>
#include <span>
#include <cstdio>
#include <concepts>

using ByteSpan = std::span<const std::byte>;

// ---- endianness helpers ---------------------------------------------------
// C++23 gives std::byteswap. These wrappers read a big-endian field from a
// byte span and return it in host order, with no alignment assumption.

namespace detail {

template <std::integral T>
inline T load_be(ByteSpan bytes) {
    T v;
    std::memcpy(&v, bytes.data(), sizeof(T));   // safe unaligned copy
    if constexpr (std::endian::native == std::endian::little) {
        v = std::byteswap(v);               // wire is big-endian
    }
    return v;
}

} // namespace detail

// ---- message views --------------------------------------------------------

struct Header {
    std::uint8_t  version;
    std::uint8_t  msg_type;
    std::uint16_t payload_length;
    std::uint32_t sequence;

    static constexpr std::size_t WIRE_SIZE = 8;
};

struct QuoteBody {
    std::uint32_t instrument_id;
    std::int64_t  price;
    std::uint32_t size;

    static constexpr std::size_t WIRE_SIZE = 16;
    static constexpr std::uint8_t MSG_TYPE = 0x01;
};

enum class ParseStatus {
    Ok,
    Incomplete,      // buffer holds a partial frame, wait for more bytes
    BadLength,       // declared payload_length inconsistent with body
    UnknownType      // msg_type not handled
};

// ---- parser ---------------------------------------------------------------

class BinaryMessageParser {
public:
    // Attempt to read a header from the front of `bytes`.
    // On Ok, header is populated and consumed is set to the total frame
    // size (header + payload) so the caller can advance the read cursor.
    ParseStatus parse_header(ByteSpan bytes,
                             Header& out,
                             std::size_t& frame_size) const {
        if (bytes.size() < Header::WIRE_SIZE) {
            return ParseStatus::Incomplete;
        }
        out.version        = static_cast<std::uint8_t>(bytes[0]);
        out.msg_type       = static_cast<std::uint8_t>(bytes[1]);
        out.payload_length = detail::load_be<std::uint16_t>(bytes.subspan(2, 2));
        out.sequence       = detail::load_be<std::uint32_t>(bytes.subspan(4, 4));

        frame_size = Header::WIRE_SIZE + out.payload_length;
        if (bytes.size() < frame_size) {
            return ParseStatus::Incomplete;   // body not fully arrived yet
        }
        return ParseStatus::Ok;
    }

    // Parse a quote body given a header already validated by parse_header.
    // body holds exactly the bytes following the header.
    ParseStatus parse_quote(const Header& hdr,
                            ByteSpan body,
                            QuoteBody& out) const {
        if (hdr.msg_type != QuoteBody::MSG_TYPE) {
            return ParseStatus::UnknownType;
        }
        if (hdr.payload_length != QuoteBody::WIRE_SIZE) {
            return ParseStatus::BadLength;
        }
        out.instrument_id = detail::load_be<std::uint32_t>(body.subspan(0, 4));
        out.price         = static_cast<std::int64_t>(
                                detail::load_be<std::uint64_t>(body.subspan(4, 8)));
        out.size          = detail::load_be<std::uint32_t>(body.subspan(12, 4));
        return ParseStatus::Ok;
    }
};

// ---- drain loop -----------------------------------------------------------
// Typical feed-handler usage: pull as many complete frames as the buffer
// holds, hand each off, and report how many bytes were consumed so the
// caller can compact the remaining partial frame to the front.

template <typename OnQuote>
inline std::size_t drain(const BinaryMessageParser& parser,
                         ByteSpan data,
                         OnQuote&& on_quote) {
    std::size_t offset = 0;
    for (;;) {
        Header hdr;
        std::size_t frame_size = 0;
        auto st = parser.parse_header(data.subspan(offset), hdr, frame_size);
        if (st == ParseStatus::Incomplete) {
            break;                            // wait for the next socket read
        }

        ByteSpan body = data.subspan(offset + Header::WIRE_SIZE,
                                     frame_size - Header::WIRE_SIZE);
        if (hdr.msg_type == QuoteBody::MSG_TYPE) {
            QuoteBody q;
            if (parser.parse_quote(hdr, body, q) == ParseStatus::Ok) {
                on_quote(hdr, q);
            }
            // A bad body is dropped here; a real handler would log and
            // decide whether the stream needs a resync.
        }
        // Unknown types are skipped by frame_size, which keeps the parser
        // forward-compatible with message types it does not yet decode.

        offset += frame_size;
    }
    return offset;                            // bytes fully consumed
}

int main(){
    // One quote frame, hand-encoded big-endian on the wire:
    //   header: version=1, msg_type=0x01, payload_length=16, sequence=42
    //   body:   instrument_id=7, price=123456, size=100
    std::byte raw[] = {
        // header
        std::byte{0x01}, std::byte{0x01},             // version, msg_type
        std::byte{0x00}, std::byte{0x10},              // payload_length = 16
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x2A}, // sequence = 42
        // body
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x07}, // instrument_id = 7
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x00},
        std::byte{0x00}, std::byte{0x01}, std::byte{0xE2}, std::byte{0x40}, // price = 123456
        std::byte{0x00}, std::byte{0x00}, std::byte{0x00}, std::byte{0x64}, // size = 100
    };

    BinaryMessageParser parser;
    std::size_t consumed = drain(parser, ByteSpan{raw}, [](const Header& hdr, const QuoteBody& q) {
        std::printf("seq=%u instrument=%u price=%lld size=%u\n",
                    hdr.sequence, q.instrument_id,
                    static_cast<long long>(q.price), q.size);
    });

    std::printf("consumed %zu of %zu bytes\n", consumed, sizeof(raw));
    return 0;
}


