// Generated by Claude, 2026-08-14

// Canonical fixed-size object pool.
// Pre-allocates N objects of type T at construction. Acquire and release
// are O(1) and allocation-free. Not thread-safe by default; a single
// atomic free-list swap can be added for MPSC use if the interviewer
// pushes on concurrency.


#include <array>
#include <cstddef>
#include <vector>
#include <stdexcept>
#include <new>
#include <utility>

template <typename T>
class ObjectPool {
public:
    explicit ObjectPool(std::size_t capacity)
        : capacity_(capacity),
          storage_(static_cast<T*>(::operator new(capacity * sizeof(T)))),
          free_list_(capacity)
    {
        // Free list holds raw slot pointers, LIFO order.
        // Index 0 is pushed last so it pops first, matching first-touch
        // locality on a freshly constructed pool.
        for (std::size_t i = 0; i < capacity_; ++i) {
            free_list_[i] = storage_ + (capacity_ - 1 - i);
        }
        free_top_ = capacity_;
    }

    ~ObjectPool() {
        ::operator delete(storage_);
    }

    ObjectPool(const ObjectPool&) = delete;
    ObjectPool& operator=(const ObjectPool&) = delete;

    // Acquire a slot and construct T in place with the given arguments.
    // Returns nullptr if the pool is exhausted, so the caller can decide
    // whether to drop, block, or grow, rather than throwing on the hot path.
    template <typename... Args>
    T* acquire(Args&&... args) {
        if (free_top_ == 0) {
            return nullptr;
        }
        T* slot = free_list_[--free_top_];
        return ::new (static_cast<void*>(slot)) T(std::forward<Args>(args)...);
    }

    // Destroy the object and return its slot to the free list.
    void release(T* obj) {
        if (obj == nullptr) {
            return;
        }
        obj->~T();
        free_list_[free_top_++] = obj;
    }

    std::size_t capacity() const { return capacity_; }
    std::size_t in_use() const { return capacity_ - free_top_; }
    std::size_t available() const { return free_top_; }

private:
    std::size_t capacity_;
    T* storage_;                       // contiguous, uninitialised backing store
    std::vector<T*> free_list_;        // stack of free slot pointers
    std::size_t free_top_;             // number of valid entries in free_list_
};



// Fixed-capacity variant: N decided at compile time, so the backing store
// can live inline as a std::array of aligned raw storage instead of a
// heap allocation from ::operator new. Same acquire/release contract as
// ObjectPool, but no allocation at all, even at construction.
template <typename T, std::size_t N>
class FixedObjectPool {
public:
    FixedObjectPool() {
        // Free list holds raw slot pointers, LIFO order, matching
        // ObjectPool's first-touch locality on a freshly constructed pool.
        for (std::size_t i = 0; i < N; ++i) {
            free_list_[i] = slot_ptr(N - 1 - i);
        }
        free_top_ = N;
    }

    FixedObjectPool(const FixedObjectPool&) = delete;
    FixedObjectPool& operator=(const FixedObjectPool&) = delete;

    template <typename... Args>
    T* acquire(Args&&... args) {
        if (free_top_ == 0) {
            return nullptr;
        }
        T* slot = free_list_[--free_top_];
        return ::new (static_cast<void*>(slot)) T(std::forward<Args>(args)...);
    }

    void release(T* obj) {
        if (obj == nullptr) {
            return;
        }
        obj->~T();
        free_list_[free_top_++] = obj;
    }

    std::size_t capacity() const { return N; }
    std::size_t in_use() const { return N - free_top_; }
    std::size_t available() const { return free_top_; }

private:
    T* slot_ptr(std::size_t i) {
        return std::launder(reinterpret_cast<T*>(&storage_[i * sizeof(T)]));
    }

    // Uninitialised, correctly aligned storage for N objects of type T,
    // inline in the pool rather than heap-allocated.
    alignas(T) std::array<std::byte, sizeof(T) * N> storage_;
    std::array<T*, N> free_list_;
    std::size_t free_top_;
};

int main(){
    return 1;
}

