// Generated by Claude (Opus 5.5), 2026-10-03
// rolling-sum-regression-test.cpp
// Regression test for RollingSum: fixed input, brute-force reference, frozen output.
//
// Build (from src/feed-handler):
//   g++-14 -std=c++23 -g -fsanitize=address,undefined rolling-sum-regression-test.cpp -o ../../build/rolling-sum-regression-test
//   g++-14 -std=c++23 -O2 rolling-sum-regression-test.cpp -o ../../build/rolling-sum-regression-test
// Run:
//   ../../build/rolling-sum-regression-test            # exit code 0 = pass
//   ../../build/rolling-sum-regression-test --print    # print hashes to freeze, skip hash checks
//
// Three layers:
//   1. Input fingerprint: the corpus must be the one the hashes were frozen against.
//   2. Reference: RollingSum must match a brute-force rolling sum after every tick.
//   3. Frozen output: the hash of the sequence of sums must match the stored constant.
// If 1 fails, the generator (or the C library's log) changed, not RollingSum.
// If 3 fails but 2 passes, RollingSum and the reference changed together: the
// window rules were changed on purpose and the hashes need re-freezing.

#include "rolling-sum.hpp"
#include "tick-generator.hpp"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <deque>
#include <utility>
#include <vector>

// ---------------------------------------------------------------------------
// Frozen values. Re-freeze with --print, only after the reference check passes.
// ---------------------------------------------------------------------------
static constexpr std::size_t   kCorpusSize = 200'000;
static constexpr std::uint64_t kInputHash  = 0x4adfde5164e89905ULL;

static constexpr std::uint64_t kHash_10x1ms   = 0x0ce633a9caabf84eULL;
static constexpr std::uint64_t kHash_1x1ms    = 0x8e00e3b16c595058ULL;
static constexpr std::uint64_t kHash_64x100us = 0x8b1d360dd9b59ac0ULL;
static constexpr std::uint64_t kHash_10x3s    = 0x988c6d924fd9dc26ULL;

// ---------------------------------------------------------------------------
// FNV-1a 64-bit, fed one int64 at a time, low byte first (endian independent).
// ---------------------------------------------------------------------------
struct Fnv1a {
    std::uint64_t h = 0xcbf29ce484222325ULL;
    void add(std::int64_t v) {
        auto u = static_cast<std::uint64_t>(v);
        for (int i = 0; i < 8; ++i) {
            h ^= (u >> (8 * i)) & 0xff;
            h *= 0x100000001b3ULL;
        }
    }
};

// ---------------------------------------------------------------------------
// Reference. Same rules as RollingSum, different data structure:
//   - bucket = ts_ns / bucket_ns
//   - a tick whose bucket is older than the newest bucket seen is dropped
//   - the sum covers the newest nbuckets buckets: (bucket - nbuckets, bucket]
// Keeps every live tick in a deque. The running sum is re-counted from the
// deque every kRecount ticks to check the reference against itself.
// ---------------------------------------------------------------------------
class ReferenceSum {
public:
    ReferenceSum(std::int64_t nbuckets, std::int64_t bucket_ns)
        : nbuckets_(nbuckets), bucket_ns_(bucket_ns) {}

    void on_tick(const Tick& t) {
        const std::int64_t bucket = t.ts_ns / bucket_ns_;
        if (bucket < last_bucket_) return;
        last_bucket_ = bucket;

        while (!live_.empty() && live_.front().first <= bucket - nbuckets_) {
            sum_ -= live_.front().second;
            live_.pop_front();
        }
        live_.emplace_back(bucket, t.qty);
        sum_ += t.qty;
    }

    std::int64_t sum() const { return sum_; }

    std::int64_t recount() const {
        std::int64_t s = 0;
        for (const auto& e : live_) s += e.second;
        return s;
    }

private:
    std::int64_t nbuckets_, bucket_ns_;
    std::int64_t last_bucket_ = 0;
    std::int64_t sum_ = 0;
    std::deque<std::pair<std::int64_t, std::int64_t>> live_;
};

static int  g_failures = 0;
static bool g_print    = false;

static void check_hash(const char* what, std::uint64_t got, std::uint64_t frozen) {
    if (g_print) {
        std::printf("  %-16s 0x%016llxULL\n", what, static_cast<unsigned long long>(got));
    } else if (got != frozen) {
        std::printf("FAIL  %s: hash 0x%016llx, frozen 0x%016llx\n", what,
                    static_cast<unsigned long long>(got), static_cast<unsigned long long>(frozen));
        ++g_failures;
    } else {
        std::printf("ok    %s: hash matches\n", what);
    }
}

// ---------------------------------------------------------------------------
// Layers 2 and 3 for one configuration.
// ---------------------------------------------------------------------------
template <std::size_t NBuckets, std::int64_t BucketNs>
static void run_config(const char* name, const std::vector<Tick>& ticks, std::uint64_t frozen) {
    static constexpr std::size_t kRecount = 4096;

    RollingSum<NBuckets, BucketNs> sum;
    ReferenceSum ref(static_cast<std::int64_t>(NBuckets), BucketNs);
    Fnv1a hash;
    std::int64_t bucket_changes = 0, prev_bucket = -1;

    for (std::size_t i = 0; i < ticks.size(); ++i) {
        const Tick& t = ticks[i];
        sum.on_tick(t);
        ref.on_tick(t);

        if (i % kRecount == 0 && ref.sum() != ref.recount()) {
            std::printf("FAIL  %s: reference is inconsistent at tick %zu\n", name, i);
            ++g_failures;
            return;
        }

        const std::int64_t got = sum.get_sum();
        if (got != ref.sum()) {
            std::printf("FAIL  %s: first mismatch at tick %zu (ts_ns=%lld qty=%lld): "
                        "RollingSum=%lld reference=%lld\n",
                        name, i, static_cast<long long>(t.ts_ns), static_cast<long long>(t.qty),
                        static_cast<long long>(got), static_cast<long long>(ref.sum()));
            ++g_failures;
            return;
        }
        hash.add(got);

        if (t.ts_ns / BucketNs != prev_bucket) { ++bucket_changes; prev_bucket = t.ts_ns / BucketNs; }
    }

    if (!g_print)
        std::printf("ok    %s: matches reference on %zu ticks (%lld bucket changes)\n",
                    name, ticks.size(), static_cast<long long>(bucket_changes));
    check_hash(name, hash.h, frozen);
}

// ---------------------------------------------------------------------------
// Hand-written cases with sums worked out by hand. These cover paths the
// corpus cannot reach (late ticks) and exact boundaries.
// ---------------------------------------------------------------------------
#define EXPECT_SUM(agg, expected)                                                        \
    do {                                                                                 \
        if ((agg).get_sum() != (expected)) {                                             \
            std::printf("FAIL  edge case, line %d: sum=%lld expected=%lld\n", __LINE__,  \
                        static_cast<long long>((agg).get_sum()),                         \
                        static_cast<long long>(expected));                               \
            ++g_failures;                                                                \
        }                                                                                \
    } while (0)

static void edge_cases() {
    const int before = g_failures;

    {   // 4 buckets of 10 ns: boundaries, expiry, late ticks, zero quantity
        RollingSum<4, 10> s;
        EXPECT_SUM(s, 0);
        s.on_tick({0, 1, 5});   EXPECT_SUM(s, 5);
        s.on_tick({9, 1, 3});   EXPECT_SUM(s, 8);    // last ns of bucket 0
        s.on_tick({10, 1, 2});  EXPECT_SUM(s, 10);   // first ns of bucket 1
        s.on_tick({39, 1, 1});  EXPECT_SUM(s, 11);   // bucket 3, nothing expired yet
        s.on_tick({40, 1, 1});  EXPECT_SUM(s, 4);    // bucket 4 expires bucket 0 (8)
        s.on_tick({35, 1, 100}); EXPECT_SUM(s, 4);   // late tick (bucket 3): dropped
        s.on_tick({41, 1, 0});  EXPECT_SUM(s, 4);    // zero quantity
        s.on_tick({40, 1, 6});  EXPECT_SUM(s, 10);   // older timestamp, same bucket: kept
    }
    {   // gap of nbuckets - 1 buckets: the old bucket is still inside the window
        RollingSum<4, 10> s;
        s.on_tick({0, 1, 7});
        s.on_tick({30, 1, 1});  EXPECT_SUM(s, 8);
    }
    {   // gap of exactly nbuckets buckets: the old bucket has just left
        RollingSum<4, 10> s;
        s.on_tick({0, 1, 7});
        s.on_tick({40, 1, 1});  EXPECT_SUM(s, 1);
    }
    {   // gap of nbuckets + 1 buckets: long silence
        RollingSum<4, 10> s;
        s.on_tick({0, 1, 7});
        s.on_tick({50, 1, 1});  EXPECT_SUM(s, 1);
    }
    {   // first tick far from zero
        RollingSum<4, 10> s;
        const std::int64_t far = 1'000'000'000'000'000'000;
        s.on_tick({far, 1, 9});      EXPECT_SUM(s, 9);
        s.on_tick({far + 10, 1, 1}); EXPECT_SUM(s, 10);
        s.on_tick({far + 40, 1, 1}); EXPECT_SUM(s, 2);
    }
    {   // a single bucket
        RollingSum<1, 10> s;
        s.on_tick({0, 1, 5});   EXPECT_SUM(s, 5);
        s.on_tick({5, 1, 1});   EXPECT_SUM(s, 6);
        s.on_tick({10, 1, 2});  EXPECT_SUM(s, 2);
    }

    if (g_failures == before) std::printf("ok    edge cases\n");
}

int main(int argc, char** argv) {
    g_print = argc > 1 && std::strcmp(argv[1], "--print") == 0;

    edge_cases();

    const std::vector<Tick> ticks = TickGenerator::corpus(kCorpusSize);

    Fnv1a in;
    for (const Tick& t : ticks) { in.add(t.ts_ns); in.add(t.price); in.add(t.qty); }
    const int before_input = g_failures;
    check_hash("input corpus", in.h, kInputHash);
    if (g_failures != before_input) {
        std::printf("Input differs from the frozen corpus; output hashes are not comparable.\n");
        return 1;
    }

    run_config<10, 1'000'000>("10 x 1ms", ticks, kHash_10x1ms);
    run_config<1, 1'000'000>("1 x 1ms", ticks, kHash_1x1ms);
    run_config<64, 100'000>("64 x 100us", ticks, kHash_64x100us);
    run_config<10, 3'000'000'000>("10 x 3s", ticks, kHash_10x3s);

    if (g_failures) {
        std::printf("FAILED: %d check(s)\n", g_failures);
        return 1;
    }
    std::printf(g_print ? "Reference checks passed; hashes above are ready to freeze.\n"
                        : "PASSED\n");
    return 0;
}
