#pragma once
// Generated by Claude (Opus 5.5), 2026-10-01
// tick-generator.hpp
// Deterministic synthetic tick stream for aggregation testing.
// Reproducible across platforms: only the engine is used, never a
// std::uniform_real_distribution, whose output is implementation defined.

#include "tick.hpp"

#include <cmath>
#include <cstdint>
#include <random>
#include <vector>

class TickGenerator {
public:
    struct Config {
        std::uint64_t seed        = 0x5EEDC0FFEE1234ULL;
        std::uint64_t start_ns    = 0;
        std::int64_t  start_price = 1'000'000;   // 100.0000
        double        busy_rate   = 200'000.0;   // ticks/sec in a burst
        double        quiet_rate  = 500.0;       // ticks/sec when calm
        double        burst_prob  = 0.30;        // fraction of time bursting
        std::uint64_t regime_ns   = 2'000'000'000ULL; // regime length
    };

    explicit TickGenerator(Config c) : cfg_(c),
        gap_(c.seed), px_(c.seed ^ 0x1111), qty_(c.seed ^ 0x2222),
        regime_(c.seed ^ 0x3333), now_(c.start_ns), price_(c.start_price),
        regime_end_(c.start_ns) {}

    Tick next() {
        if (now_ >= regime_end_) {
            busy_ = unit(regime_) < cfg_.burst_prob;
            regime_end_ = now_ + cfg_.regime_ns;
        }
        const double rate = busy_ ? cfg_.busy_rate : cfg_.quiet_rate;
        // exponential inter-arrival: -ln(U)/rate  -> Poisson process
        const double u = unit(gap_);
        const double gap_s = -std::log(u > 0.0 ? u : 1e-12) / rate;
        now_ += static_cast<std::uint64_t>(gap_s * 1e9) + 1;  // +1: strictly increasing

        // price: integer random walk, +/- up to 5 ticks of 1e-4
        price_ += static_cast<std::int64_t>(px_() % 11) - 5;
        if (price_ < 1) price_ = 1;

        return Tick{static_cast<std::int64_t>(now_), price_,
                    static_cast<std::int64_t>(1 + qty_() % 1000)};
    }

    // Reproducible corpus, plus deliberate edge cases at known indices.
    static std::vector<Tick> corpus(std::size_t n) { return corpus(n, Config{}); }

    static std::vector<Tick> corpus(std::size_t n, Config c) {
        TickGenerator g(c);
        std::vector<Tick> v;
        v.reserve(n + 4);
        for (std::size_t i = 0; i < n; ++i) {
            v.push_back(g.next());
            if (i == n / 4) {                       // gap longer than any window
                g.now_ += 60'000'000'000ULL;
            } else if (i == n / 2) {                // three identical timestamps
                v.push_back(Tick{v.back().ts_ns, v.back().price + 7, 10});
                v.push_back(Tick{v.back().ts_ns, v.back().price - 3, 20});
            } else if (i == 3 * n / 4) {            // zero quantity
                v.back().qty = 0;
            }
        }
        return v;
    }

private:
    static double unit(std::mt19937_64& e) {
        return static_cast<double>(e() >> 11) * (1.0 / 9007199254740992.0);
    }

    Config cfg_;
    std::mt19937_64 gap_, px_, qty_, regime_;
    std::uint64_t now_;
    std::int64_t  price_;
    std::uint64_t regime_end_;
    bool busy_ = false;
};
